'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1026
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1026.
'
Namespace UBSMS
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="SendSMS2Soap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class SendSMS2
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private Send_SMSOperationCompleted As System.Threading.SendOrPostCallback
        
        Private Send_SMS1OperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.testSMSGateway_WS.My.MySettings.Default.testSMSGateway_WS_UBSMS_SendSMS2
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event Send_SMSCompleted As Send_SMSCompletedEventHandler
        
        '''<remarks/>
        Public Event Send_SMS1Completed As Send_SMS1CompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ASM", RequestElementName:="ASM", RequestNamespace:="http://tempuri.org/", ResponseElementName:="ASMResponse", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Overloads Function Send_SMS(ByVal Mobile_NO As String, ByVal Message As String, ByVal FName As String, ByVal LName As String, ByVal Title As String, ByVal User As String, ByVal Password As String, ByVal Priority As String) As <System.Xml.Serialization.XmlElementAttribute("ASMResult")> String
            Dim results() As Object = Me.Invoke("Send_SMS", New Object() {Mobile_NO, Message, FName, LName, Title, User, Password, Priority})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Send_SMSAsync(ByVal Mobile_NO As String, ByVal Message As String, ByVal FName As String, ByVal LName As String, ByVal Title As String, ByVal User As String, ByVal Password As String, ByVal Priority As String)
            Me.Send_SMSAsync(Mobile_NO, Message, FName, LName, Title, User, Password, Priority, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Send_SMSAsync(ByVal Mobile_NO As String, ByVal Message As String, ByVal FName As String, ByVal LName As String, ByVal Title As String, ByVal User As String, ByVal Password As String, ByVal Priority As String, ByVal userState As Object)
            If (Me.Send_SMSOperationCompleted Is Nothing) Then
                Me.Send_SMSOperationCompleted = AddressOf Me.OnSend_SMSOperationCompleted
            End If
            Me.InvokeAsync("Send_SMS", New Object() {Mobile_NO, Message, FName, LName, Title, User, Password, Priority}, Me.Send_SMSOperationCompleted, userState)
        End Sub
        
        Private Sub OnSend_SMSOperationCompleted(ByVal arg As Object)
            If (Not (Me.Send_SMSCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Send_SMSCompleted(Me, New Send_SMSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.WebMethodAttribute(MessageName:="Send_SMS1"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Send_SMS", RequestElementName:="Send_SMS", RequestNamespace:="http://tempuri.org/", ResponseElementName:="Send_SMSResponse", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Overloads Function Send_SMS(ByVal Msg_ID As String, ByVal Mobile_NO As String, ByVal Body As String, ByVal Validty As String, ByVal StartTime As String, ByVal Sender As String, ByVal User As String, ByVal Password As String, ByVal Service As String) As <System.Xml.Serialization.XmlElementAttribute("Send_SMSResult")> String
            Dim results() As Object = Me.Invoke("Send_SMS1", New Object() {Msg_ID, Mobile_NO, Body, Validty, StartTime, Sender, User, Password, Service})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Send_SMS1Async(ByVal Msg_ID As String, ByVal Mobile_NO As String, ByVal Body As String, ByVal Validty As String, ByVal StartTime As String, ByVal Sender As String, ByVal User As String, ByVal Password As String, ByVal Service As String)
            Me.Send_SMS1Async(Msg_ID, Mobile_NO, Body, Validty, StartTime, Sender, User, Password, Service, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Send_SMS1Async(ByVal Msg_ID As String, ByVal Mobile_NO As String, ByVal Body As String, ByVal Validty As String, ByVal StartTime As String, ByVal Sender As String, ByVal User As String, ByVal Password As String, ByVal Service As String, ByVal userState As Object)
            If (Me.Send_SMS1OperationCompleted Is Nothing) Then
                Me.Send_SMS1OperationCompleted = AddressOf Me.OnSend_SMS1OperationCompleted
            End If
            Me.InvokeAsync("Send_SMS1", New Object() {Msg_ID, Mobile_NO, Body, Validty, StartTime, Sender, User, Password, Service}, Me.Send_SMS1OperationCompleted, userState)
        End Sub
        
        Private Sub OnSend_SMS1OperationCompleted(ByVal arg As Object)
            If (Not (Me.Send_SMS1CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Send_SMS1Completed(Me, New Send_SMS1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub Send_SMSCompletedEventHandler(ByVal sender As Object, ByVal e As Send_SMSCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Send_SMSCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub Send_SMS1CompletedEventHandler(ByVal sender As Object, ByVal e As Send_SMS1CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Send_SMS1CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
